# Generated by Django 6.0.1 on 2026-01-30 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meal_plans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_calories', models.FloatField(default=2000)),
                ('daily_protein', models.FloatField(default=150, help_text='in grams')),
                ('daily_carbs', models.FloatField(default=250, help_text='in grams')),
                ('daily_fats', models.FloatField(default=70, help_text='in grams')),
                ('daily_fiber', models.FloatField(default=30, help_text='in grams')),
                ('protein_percentage', models.IntegerField(default=30)),
                ('carbs_percentage', models.IntegerField(default=40)),
                ('fats_percentage', models.IntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NutritionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('calories_consumed', models.FloatField(default=0)),
                ('protein_consumed', models.FloatField(default=0)),
                ('carbs_consumed', models.FloatField(default=0)),
                ('fats_consumed', models.FloatField(default=0)),
                ('fiber_consumed', models.FloatField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('meal_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meal_plans.mealplan')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
